In [88]:
#pipeline ETL automatizado

import pandas as pd
import numpy as np

df=pd.read_csv(r'C:\Users\av-alumno\Documents\GitHub\Evalucion_Parcial_3\data\originales\FastFoodNutritionMenuV3.csv')

df.head()

,Company,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,McDonald’s,Hamburger,250,80,9,3.5,0.5,25,520,31,2,6,12,247.5
1,McDonald’s,Cheeseburger,300,110,12,6,0.5,40,750,33,2,6,15,297
2,McDonald’s,Double Cheeseburger,440,210,23,11,1.5,80,1150,34,2,7,25,433
3,McDonald’s,McDouble,390,170,19,8,1,65,920,33,2,7,22,383
4,McDonald’s,Quarter Pounder® with Cheese,510,230,26,12,1.5,90,1190,40,3,9,29,502

In [41]:
import pandas as pd
import numpy as np
df = pd.read_csv('FastFoodNutritionMenuV3.csv')
df.head()

,Company,Item,Calories,Calories from\nFat,Total Fat\n(g),Saturated Fat\n(g),Trans Fat\n(g),Cholesterol\n(mg),Sodium \n(mg),Carbs\n(g),Fiber\n(g),Sugars\n(g),Protein\n(g),Weight Watchers\nPnts
0,McDonald’s,Hamburger,250,80,9,3.5,0.5,25,520,31,2,6,12,247.5
1,McDonald’s,Cheeseburger,300,110,12,6,0.5,40,750,33,2,6,15,297
2,McDonald’s,Double Cheeseburger,440,210,23,11,1.5,80,1150,34,2,7,25,433
3,McDonald’s,McDouble,390,170,19,8,1,65,920,33,2,7,22,383
4,McDonald’s,Quarter Pounder® with Cheese,510,230,26,12,1.5,90,1190,40,3,9,29,502

# Extraer CSV

In [42]:
import pandas as pd
import logging

def extract_data(filepath):
    try:
        df = pd.read_csv(filepath)
        logging.info("Datos cargados correctamente")
        return df

    except FileNotFoundError:
        logging.error("Archivo no encontrado")
        raise

    except Exception as e:
        logging.error(f"Error inesperado: {e}")
        raise

# Limpieza

In [43]:
#revision de estructura
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147 entries, 0 to 1146
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company               1147 non-null   object
 1   Item                  1147 non-null   object
 2   Calories              1147 non-null   object
 3   Calories from
Fat     642 non-null    object
 4   Total Fat
(g)         1091 non-null   object
 5   Saturated Fat
(g)     1091 non-null   object
 6   Trans Fat
(g)         1091 non-null   object
 7   Cholesterol
(mg)      1147 non-null   object
 8   Sodium
(mg)          1147 non-null   object
 9   Carbs
(g)             1091 non-null   object
 10  Fiber
(g)             1091 non-null   object
 11  Sugars
(g)            1147 non-null   object
 12  Protein
(g)           1091 non-null   object
 13  Weight Watchers
Pnts  887 non-null    object
dtypes: object(14)
memory usage: 125.6+ KB

## Renombrar columnas

In [44]:
#Renombramos columnas
#Calories from\nFat
#Total Fat\n(g)
#Saturated Fat\n(g)

df.columns = (
    df.columns
    .str.replace("\n", "_")
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")", "")
)

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1147 entries, 0 to 1146
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Company               1147 non-null   object
 1   Item                  1147 non-null   object
 2   Calories              1147 non-null   object
 3   Calories_from_Fat     642 non-null    object
 4   Total_Fat_g           1091 non-null   object
 5   Saturated_Fat_g       1091 non-null   object
 6   Trans_Fat_g           1091 non-null   object
 7   Cholesterol_mg        1147 non-null   object
 8   Sodium__mg            1147 non-null   object
 9   Carbs_g               1091 non-null   object
 10  Fiber_g               1091 non-null   object
 11  Sugars_g              1147 non-null   object
 12  Protein_g             1091 non-null   object
 13  Weight_Watchers_Pnts  887 non-null    object
dtypes: object(14)
memory usage: 125.6+ KB

## Limpiar duplicados

In [46]:
df.drop_duplicates(inplace=True)

## Manejo de nulos

In [47]:
df.isnull().sum()

Company                   0
Item                      0
Calories                  0
Calories_from_Fat       505
Total_Fat_g              56
Saturated_Fat_g          56
Trans_Fat_g              56
Cholesterol_mg            0
Sodium__mg                0
Carbs_g                  56
Fiber_g                  56
Sugars_g                  0
Protein_g                56
Weight_Watchers_Pnts    260
dtype: int64

In [48]:
df.fillna(0, inplace=True)

In [49]:
df.isnull().sum()

Company                 0
Item                    0
Calories                0
Calories_from_Fat       0
Total_Fat_g             0
Saturated_Fat_g         0
Trans_Fat_g             0
Cholesterol_mg          0
Sodium__mg              0
Carbs_g                 0
Fiber_g                 0
Sugars_g                0
Protein_g               0
Weight_Watchers_Pnts    0
dtype: int64

# Cambiar tipo de las variables

In [53]:
columnas_numericas = [
    'Calories', 'Sodium__mg', 'Total_Fat_g', 'Calories_from_Fat', 
    'Saturated_Fat_g', 'Trans_Fat_g', 'Cholesterol_mg', 'Carbs_g', 
    'Fiber_g', 'Sugars_g', 'Protein_g', 'Weight_Watchers_Pnts'
]

for col in columnas_numericas:
    df[col] = pd.to_numeric(
        df[col].astype(str).str.replace('\xa0', '', regex=False).str.replace('<', '', regex=False), 
        errors='coerce')

## Calorias negativas

In [55]:
df = df[df["Calories"] >= 0]

## Sodio negativo

In [56]:
df = df[df["Sodium__mg"] >= 0]

## Grasas negativas

In [57]:
df = df[df["Total_Fat_g"] >= 0]

## Crear variables nuevas

In [58]:
def calorie_category(x):

    if x < 300:
        return "Baja"

    elif x < 600:
        return "Media"

    else:
        return "Alta"

df["Calorie_Category"] = df["Calories"].apply(calorie_category)

In [59]:
df.head(10)

,Company,Item,Calories,Calories_from_Fat,Total_Fat_g,Saturated_Fat_g,Trans_Fat_g,Cholesterol_mg,Sodium__mg,Carbs_g,Fiber_g,Sugars_g,Protein_g,Weight_Watchers_Pnts,Calorie_Category
0,McDonald’s,Hamburger,250.0,80.0,9.0,3.5,0.5,25.0,520.0,31.0,2.0,6.0,12.0,247.5,Baja
1,McDonald’s,Cheeseburger,300.0,110.0,12.0,6.0,0.5,40.0,750.0,33.0,2.0,6.0,15.0,297.0,Media
2,McDonald’s,Double Cheeseburger,440.0,210.0,23.0,11.0,1.5,80.0,1150.0,34.0,2.0,7.0,25.0,433.0,Media
3,McDonald’s,McDouble,390.0,170.0,19.0,8.0,1.0,65.0,920.0,33.0,2.0,7.0,22.0,383.0,Media
4,McDonald’s,Quarter Pounder® with Cheese,510.0,230.0,26.0,12.0,1.5,90.0,1190.0,40.0,3.0,9.0,29.0,502.0,Media
5,McDonald’s,Double Quarter Pounder® with Cheese,740.0,380.0,42.0,19.0,2.5,155.0,1380.0,40.0,3.0,9.0,48.0,720.0,Alta
6,McDonald’s,Big Mac®,540.0,260.0,29.0,10.0,1.5,75.0,1040.0,45.0,3.0,9.0,25.0,534.0,Media
7,McDonald’s,Big N’ Tasty®,460.0,220.0,24.0,8.0,1.5,70.0,720.0,37.0,3.0,8.0,24.0,452.0,Media
8,McDonald’s,Big N’ Tasty® with Cheese,510.0,250.0,28.0,11.0,1.5,85.0,960.0,38.0,3.0,8.0,27.0,502.0,Media
9,McDonald’s,Angus Bacon & Cheese,790.0,350.0,39.0,17.0,2.0,145.0,2070.0,63.0,4.0,13.0,45.0,775.0,Alta